# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rhytm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rhytm

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'


  target 'RhytmTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RhytmUITests' do
    # Pods for testing
  end

end
